/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edd.practica1.visual;

import edd.practica1.logica.Correr;

/**
 *
 * @author Saul
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        componentStart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlanta = new javax.swing.JButton();
        btnZombie = new javax.swing.JButton();
        lblPlantas = new javax.swing.JLabel();
        lblZombies = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPlanta.setText("Jugador Plantas");
        btnPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlanta);
        btnPlanta.setBounds(30, 150, 140, 23);

        btnZombie.setText("Jugador Zombies");
        btnZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZombieActionPerformed(evt);
            }
        });
        getContentPane().add(btnZombie);
        btnZombie.setBounds(240, 150, 150, 23);

        lblPlantas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/icons/flower81.png"))); // NOI18N
        getContentPane().add(lblPlantas);
        lblPlantas.setBounds(40, 12, 130, 130);

        lblZombies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/icons/plant.png"))); // NOI18N
        getContentPane().add(lblZombies);
        lblZombies.setBounds(250, 10, 130, 130);

        btnComenzar.setText("Comenzar Juego");
        getContentPane().add(btnComenzar);
        btnComenzar.setBounds(70, 180, 130, 23);

        btnEliminar.setText("Eliminar Datos");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(210, 180, 140, 23);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 50, 73, 23);

        setBounds(0, 0, 430, 254);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantaActionPerformed
        Correr.panJugador.setVisible(true);
        Correr.panJugador.componentStart();
        Correr.panJugador.tipoJugador(true);
    }//GEN-LAST:event_btnPlantaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       newCorrer.generarArchivo("listaJ.txt");
       newCorrer.archivoLista(0);
       newCorrer.generarGraph("listaJ");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZombieActionPerformed
        Correr.panJugador.setVisible(true);
        Correr.panJugador.componentStart();
        Correr.panJugador.tipoJugador(false);
    }//GEN-LAST:event_btnZombieActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Correr.listaJ.vaciarLista();
        Correr.listaP.vaciarLista();
        Correr.listaZ.vaciarLista();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void componentStart(){
        newCorrer = new Correr();
        newCorrer.comenzar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private Correr newCorrer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnPlanta;
    private javax.swing.JButton btnZombie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPlantas;
    private javax.swing.JLabel lblZombies;
    // End of variables declaration//GEN-END:variables
}
