/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edd.practica1.visual;

import edd.practica1.logica.Correr;
import edd.practica1.logica.Data;

/**
 *
 * @author Saul
 */
public class Jugador extends javax.swing.JFrame {

    /**
     * Creates new form Jugador
     */
    public Jugador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/icons/plant.png"))); // NOI18N
        getContentPane().add(lblIcon);
        lblIcon.setBounds(260, 10, 128, 128);

        lblJugador.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblJugador.setText("PLANTAS");
        getContentPane().add(lblJugador);
        lblJugador.setBounds(30, 60, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 160, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("CANTIDAD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 200, 90, 20);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setToolTipText("Nombre de Jugador");
        getContentPane().add(txtNombre);
        txtNombre.setBounds(140, 160, 180, 23);

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCantidad.setToolTipText("Cantidad Limite");
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(140, 200, 180, 23);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAgregar.setLabel("AGREGAR MAS CAMPOS");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(30, 250, 170, 30);

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAceptar.setLabel("FINALIZAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(220, 250, 120, 30);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //if(!guardado)
            guardarDatos();
        /*Correr.listaJ.print();
        System.out.println("primer listar");
        edd.practica1.logica.Nodo nod = Correr.listaJ.getPrimero();
        datos = new Data();
        datos.setNombre(txt1.getText());
        nod.getDatos().getLista().InsertarFrente(datos);
        datos = new Data();
        datos.setNombre(txt2.getText());
        nod.getDatos().getLista().InsertarFrente(datos);
        nod.getDatos().getLista().print();
        System.out.println("segundo listar");*/
        this.hide();
        Correr.panAvatar.setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed
    private void guardarDatos(){
        Data datos = new Data();
        datos.setNombre(txtNombre.getText());
        datos.setCantidad(Integer.parseInt(txtCantidad.getText()));
        if(tipoA)datos.setTipo(1);
        else datos.setTipo(2);
        Correr.listaJ.InsertarFrente(datos);
        guardado = true;
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        guardarDatos();
        new Campos().setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed
    public void componentStart(){
        txtNombre.setText(null);
        txtCantidad.setText(null);
    }
    public void tipoJugador(boolean tipo){
        tipoA = tipo;
        if(tipo){
            lblJugador.setText("PLANTA");
            lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/icons/plant.png")));
        }else{
            lblJugador.setText("ZOMBIE");
            lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/icons/zombie.png")));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador().setVisible(true);
            }
        });
    }
    public static boolean tipoA;
    private boolean guardado = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
