/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edd.practica1.visual;

import edd.practica1.logica.Correr;
import edd.practica1.logica.Data;

/**
 *
 * @author Saul
 */
public class NuevoAvatar extends javax.swing.JFrame {

    /**
     * Creates new form NuevoAvatar
     */
    public NuevoAvatar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblNombre = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        txtPuntos = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        txtImagen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setText("NOMBRE");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(29, 44, 60, 17);

        lblAtaque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAtaque.setText("ATAQUE");
        getContentPane().add(lblAtaque);
        lblAtaque.setBounds(30, 80, 60, 20);

        lblPuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuntos.setText("PUNTOS");
        getContentPane().add(lblPuntos);
        lblPuntos.setBounds(30, 120, 52, 17);

        lblImagen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImagen.setText("IMAGEN");
        getContentPane().add(lblImagen);
        lblImagen.setBounds(30, 160, 60, 20);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(100, 40, 190, 20);
        getContentPane().add(txtAtaque);
        txtAtaque.setBounds(100, 80, 190, 20);
        getContentPane().add(txtPuntos);
        txtPuntos.setBounds(100, 120, 190, 20);

        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(200, 190, 150, 30);
        getContentPane().add(txtImagen);
        txtImagen.setBounds(100, 160, 190, 20);

        setBounds(0, 0, 388, 272);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Data datos = new Data(txtNombre.getText(),txtImagen.getText(),txtAtaque.getText(),Integer.parseInt(txtPuntos.getText()));
        if(Correr.panJugador.tipoA){
            Correr.listaP.InsertarFinal(datos);
        }else{
            Correr.listaZ.InsertarFinal(datos);
        }
        this.dispose();
        Correr.panAvatar.setVisible(true);
        Correr.panAvatar.ListarAvatares();
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoAvatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuntos;
    // End of variables declaration//GEN-END:variables
}
